### ISSUE TITLE
bedrock_server.sh の wget で Minecraft.net に接続ができません。

### ISSUE THREAD

**Issue by G20100** [ktooi/docker-minecraft-bedrock#1]

**Comment by G20100** [comment]
Line 14 の wget に --user-agent=AGENT オプションを入れると通ったので、UserAgent 指定を入れていただけないでしょうか。

**Comment by ktooi** [comment]
@G20100
ご指摘ありがとうございます。

最新版(7891abb8430948ea4f492bcd489c1fae24b080a3)は `curl` に変更してあるのですが、こちらの対応でいかがでしょう？

**Comment by ktooi** [comment]
@G20100 
すみません、 `curl` でも動かなくなっていました。対応します。

**Comment by ktooi** [comment]
@G20100 
コマンドは `curl` のままですが、 User Agent を設定することで minecraft.net へ接続できるように修正しました。

`wget` のパターンも検証したのですが、ご提案頂いたように `--user-agent=AGENT` そのままだと接続ができるようになるものの、よりリアルなブラウザの UA を指定すると接続できなくなってしまいました。
i. e.,
```shell-session
$ wget --version
GNU Wget 1.20.1 built on linux-gnu.

...snip...

$ wget '--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36' https://www.minecraft.net/en-us
/download/server/bedrock/ -O - 
--2021-07-17 15:01:09--  https://www.minecraft.net/en-us/download/server/bedrock/
Resolving www.minecraft.net (www.minecraft.net)... 210.132.245.42, 210.132.245.74
Connecting to www.minecraft.net (www.minecraft.net)|210.132.245.42|:443... connected.
HTTP request sent, awaiting response... 
(ここで応答が止まる)
```

このため、今回は `curl` の利用を継続しています。

なお、 UA の変更は環境変数の `USER_AGENT` を指定することで可能になっているはずです。必要があれば

```shell-session
$ USER_AGENT="Your User Agent" /path/to/bedrock_server.sh
```

等として指定してください。

ご確認いただき、この対応で問題がなければ本 Issue の Close をお願いいたします。

**Comment by G20100** [comment]
おお。素晴らしい対応ありがとうございます。Close します!
